modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/right-click-harvest-supplementaries-compat/issues"

[[mods]]
modId = "rch_supplementaries_compat"
version = "${file.jarVersion}"
displayName = "RightClickHarvest Supplementaries Compat"
displayURL="https://github.com/JamCoreModding/right-click-harvest-supplementaries-compat"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Adds compatibility between RightClickHarvest and Supplementaries
'''

[[dependencies.rch_supplementaries_compat]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rch_supplementaries_compat]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rch_supplementaries_compat]]
modId = "rightclickharvest"
mandatory = true
versionRange = "[${rch_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rch_supplementaries_compat]]
modId = "supplementaries"
mandatory = true
versionRange = "[${supplementaries_version},)"
ordering = "NONE"
side = "BOTH"
