[versions]
# https://parchmentmc.org/docs/getting-started
parchment-minecraft = "1.21.1"
parchment = "2024.11.17"

# https://files.minecraftforge.net/net/minecraftforge/forge/
#forge = "1.20.1-47.3.1"

# https://fabricmc.net/develop
fabric-loader = "0.16.9"

# https://maven.jamalam.tech/#/releases/io/github/jamalam360/right-click-harvest
rightclickharvest-fabric = "4.4.4+1.21.1"
#rightclickharvest-forge = "3.2.3+1.20.1-forge"

# https://modrinth.com/mod/supplementaries/versions
supplementaries-fabric = "RihagfdB"
#supplementaries-forge = "sfePFkny"

# https://modrinth.com/mod/moonlight/versions
moonlight-fabric = "F7VRCvQQ"
#moonlight-forge = "GSDEbxNt"

# https://modrinth.com/mod/modmenu/versions
modmenu = "7.2.2"

[libraries]
#forge = { module = "net.minecraftforge:forge", version.ref = "forge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

rightclickharvest-fabric = { module = "io.github.jamalam360:rightclickharvest-fabric", version.ref = "rightclickharvest-fabric" }
#rightclickharvest-forge = { module = "io.github.jamalam360:right-click-harvest", version.ref = "rightclickharvest-forge" }

supplementaries-fabric = { module = "maven.modrinth:supplementaries", version.ref = "supplementaries-fabric" }
#supplementaries-forge = { module = "maven.modrinth:supplementaries", version.ref = "supplementaries-forge" }

moonlight-fabric = { module = "maven.modrinth:moonlight", version.ref = "moonlight-fabric" }
#moonlight-forge = { module = "maven.modrinth:moonlight", version.ref = "moonlight-forge" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
