[versions]
# https://parchmentmc.org/docs/getting-started
parchment-minecraft = "1.21.1"
parchment = "2024.11.17"

# https://projects.neoforged.net/neoforged/neoforge
neoforge = "21.1.92"

# https://fabricmc.net/develop
fabric-loader = "0.16.9"

# https://maven.jamalam.tech/#/releases/io/github/jamalam360/rightclickharvest-fabric
rightclickharvest-fabric = "4.4.4+1.21.1"

# https://maven.jamalam.tech/#/releases/io/github/jamalam360/rightclickharvest-neoforge
rightclickharvest-neoforge = "4.4.4+1.21.1"

# https://modrinth.com/mod/supplementaries/versions
supplementaries-fabric = "RihagfdB"
supplementaries-neoforge = "5UJVGbxs"

# https://modrinth.com/mod/moonlight/versions
moonlight-fabric = "F7VRCvQQ"
moonlight-neoforge = "ULfXjN2I"

# https://modrinth.com/mod/modmenu/versions
modmenu = "YIfqIJ8q"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

rightclickharvest-fabric = { module = "io.github.jamalam360:rightclickharvest-fabric", version.ref = "rightclickharvest-fabric" }
rightclickharvest-neoforge = { module = "io.github.jamalam360:rightclickharvest-neoforge", version.ref = "rightclickharvest-neoforge" }

supplementaries-fabric = { module = "maven.modrinth:supplementaries", version.ref = "supplementaries-fabric" }
supplementaries-neoforge = { module = "maven.modrinth:supplementaries", version.ref = "supplementaries-neoforge" }

moonlight-fabric = { module = "maven.modrinth:moonlight", version.ref = "moonlight-fabric" }
moonlight-neoforge = { module = "maven.modrinth:moonlight", version.ref = "moonlight-neoforge" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
